name: Build Release and Debug APKs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.13

      - name: Build Release and Debug APKs
        run: |
          chmod +x gradlew
          ./gradlew assembleStableRelease assembleStableDebug --stacktrace

      - name: Upload Release APKs
        uses: actions/upload-artifact@v4
        with:
          name: anisync-release-apk
          path: |
            app/build/outputs/apk/stable/release/*.apk

      - name: Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: anisync-debug-apk
          path: |
            app/build/outputs/apk/stable/debug/*.apk
